
name: Client Deploy ({{ENV_NAME}})
on:
  push:
    branches: [{{BRANCH_NAME}}]
    paths: ['client/**', 'shared/**']
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    environment:
      name: {{ENV_NAME}}
      url: ${{ steps.deploy.outputs.url }}
    steps:
      - uses: actions/checkout@v4
      
      - uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: '${{ secrets.GCP_WIF_PROVIDER }}'
          service_account: '${{ secrets.GCP_SA_EMAIL }}'
          
      - run: gcloud auth configure-docker ${{ vars.GCP_REGION }}-docker.pkg.dev
      
      - uses: docker/build-push-action@v5
        with:
          context: .
          file: ./client/Dockerfile
          push: true
          tags: ${{ vars.ARTIFACT_REPO }}/client:latest
          
      - id: deploy
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: client
          image: ${{ vars.ARTIFACT_REPO }}/client:latest
          region: ${{ vars.GCP_REGION }}
          env_vars: |
            NEXT_PUBLIC_API_URL=${{ vars.NEXT_PUBLIC_API_URL }}
            NEXT_PUBLIC_SUPABASE_URL=${{ vars.NEXT_PUBLIC_SUPABASE_URL }}
          secrets: |
            NEXT_PUBLIC_SUPABASE_ANON_KEY=${{ vars.GCP_PROJECT_ID }}/secrets/SUPABASE_ANON_KEY
