
name: Server Deploy ({{ENV_NAME}})
on:
  push:
    branches: [{{BRANCH_NAME}}]
    paths: ['server/**', 'shared/**']
  workflow_dispatch:
    inputs:
      update_secrets:
        description: 'Update Secrets Before Deploy?'
        type: boolean
        default: false

jobs:
  update-secrets:
    if: ${{ inputs.update_secrets == true }}
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    environment: {{ENV_NAME}}
    steps:
      - uses: actions/checkout@v4
      - uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: '${{ secrets.GCP_WIF_PROVIDER }}'
          service_account: '${{ secrets.GCP_SA_EMAIL }}'
      - run: |
          update_s() { if [ -n "$2" ]; then echo -n "$2" | gcloud secrets versions add $1 --data-file=-; fi }
          update_s "OPENAI_API_KEY" "${{ secrets.OPENAI_API_KEY }}"
          update_s "SUPABASE_URL" "${{ secrets.SUPABASE_URL }}"
          update_s "SUPABASE_ANON_KEY" "${{ secrets.SUPABASE_ANON_KEY }}"

  deploy:
    needs: [update-secrets]
    if: always() && (needs.update-secrets.result == 'success' || needs.update-secrets.result == 'skipped')
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    environment:
      name: {{ENV_NAME}}
      url: ${{ steps.deploy.outputs.url }}
    steps:
      - uses: actions/checkout@v4
      - uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: '${{ secrets.GCP_WIF_PROVIDER }}'
          service_account: '${{ secrets.GCP_SA_EMAIL }}'
          
      - run: gcloud auth configure-docker ${{ vars.GCP_REGION }}-docker.pkg.dev
      
      - uses: docker/build-push-action@v5
        with:
          context: .
          file: ./server/Dockerfile
          push: true
          tags: ${{ vars.ARTIFACT_REPO }}/server:latest
          
      - id: deploy
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: server
          image: ${{ vars.ARTIFACT_REPO }}/server:latest
          region: ${{ vars.GCP_REGION }}
          secrets: |
            SUPABASE_URL=${{ vars.GCP_PROJECT_ID }}/secrets/SUPABASE_URL
            SUPABASE_ANON_KEY=${{ vars.GCP_PROJECT_ID }}/secrets/SUPABASE_ANON_KEY
            OPENAI_API_KEY=${{ vars.GCP_PROJECT_ID }}/secrets/OPENAI_API_KEY
