import inquirer from 'inquirer';
import fs from 'fs-extra';
import path from 'path';
import chalk from 'chalk';

const ROOT_DIR = process.cwd();
const ENV_PATH = path.join(ROOT_DIR, '.env.local');

export async function run() {
    console.log(chalk.cyan('\n⚙️  Environment Configuration Wizard\n'));

    const exists = await fs.pathExists(ENV_PATH);
    if (exists) {
        const { overwrite } = await inquirer.prompt([
            {
                type: 'confirm',
                name: 'overwrite',
                message: '.env.local already exists. Do you want to update it?',
                default: false,
            }
        ]);
        if (!overwrite) {
            console.log(chalk.yellow('Skipping environment setup.\n'));
            return;
        }
    }

    const answers = await inquirer.prompt([
        {
            type: 'input',
            name: 'dbUrl',
            message: 'Database connection string:',
            default: 'postgresql://jobhunter:jobhunter@localhost:5432/jobhunter?sslmode=disable',
        },
        {
            type: 'input',
            name: 'gcsEndpoint',
            message: 'GCS Emulator endpoint:',
            default: 'http://localhost:4443',
        },
    ]);

    const envContent = `# Generated by scripts/init.ts
PORT=3001
NODE_ENV=development

# Database
DATABASE_URL=${answers.dbUrl}
DBMATE_MIGRATIONS_TABLE=jobhunter_schema_migrations

# Storage
GCS_ENDPOINT=${answers.gcsEndpoint}
GCS_PROJECT_ID=local-dev
RESOURCE_PREFIX=jobhunter-local
`;

    await fs.writeFile(ENV_PATH, envContent);
    const localEnvPath = path.join(ROOT_DIR, 'local.env');
    await fs.writeFile(localEnvPath, envContent);
    // Also copy to server for direct access if needed
    await fs.copy(localEnvPath, path.join(ROOT_DIR, 'server', 'local.env'));
    await fs.copy(localEnvPath, path.join(ROOT_DIR, 'server', '.env.local')).catch(() => { }); // try but ignore fail
}
